"use client";

import Link from "next/link";
import Image from "next/image";
import { useSearchParams } from "next/navigation";
import { type RefObject, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, BellRing, ChevronRight, ClipboardList, ExternalLink, FileCheck2, LogOut, Map, Menu, Navigation, Play, RefreshCw, Send, ShieldCheck, Siren, Square, UsersRound, Volume2, X } from "lucide-react";
import { useAdminSession } from "@/components/admin/AdminSessionProvider";
import { getAdminCommunes } from "@/services/admin-scope-service";
import { getAuditEntries, getAlerts, getDeliveryIncidents, getSpeakers, getUnreachedRecipients, markRecipientContacted, retryAlert } from "@/services/delivery-service";
import { getScopedRisks } from "@/services/risk-service";
import type { AdminAlert, AdminCommune, AuditEntry, CommuneRisk, DeliveryIncident, Speaker, UnreachedRecipients } from "@/types/admin-console";
import type { SOSRequest, SOSStatus } from "@/types/sos";
import { createGoogleMapsDirectionsUrl, getSos, getSosDetail, updateSosStatus } from "@/services/sos-service";

export type AdminPage = "overview" | "alerts" | "delivery" | "sos" | "speakers" | "audit";
const nav: Array<{ page: AdminPage; href: string; label: string; icon: typeof Map }> = [{ page: "overview", href: "/admin", label: "Tổng quan", icon: Map }, { page: "alerts", href: "/admin/alerts", label: "Cảnh báo", icon: AlertTriangle }, { page: "delivery", href: "/admin/delivery", label: "Gửi tin & sự cố", icon: Send }, { page: "sos", href: "/admin/sos", label: "SOS khẩn cấp", icon: Siren }, { page: "speakers", href: "/admin/speakers", label: "Loa truyền thanh", icon: Volume2 }, { page: "audit", href: "/admin/audit", label: "Nhật ký tương tác", icon: ClipboardList }];
const formatDate = (value: string) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
const hazardLabel = (hazard: string) => ({ flash_flood: "Lũ quét", heavy_rain: "Mưa lớn", fog: "Sương mù", landslide: "Sạt lở" }[hazard.toLowerCase()] ?? hazard);
const alertStatusLabel = (status: string) => ({ pending_approval: "Chờ phê duyệt", partial_failed: "Gửi một phần thất bại", sent: "Đã gửi", failed: "Gửi thất bại" }[status.toLowerCase()] ?? status);
const sosStatusLabel = (status: SOSStatus) => ({ NEW: "Mới", ACKNOWLEDGED: "Đã tiếp nhận", DISPATCHED: "Đang điều phối", RESCUED: "Đã cứu trợ", CANCELLED: "Đã hủy" }[status]);
const speakerBroadcasts = [
  { id: "broadcast-001", speakerId: "sp-01", title: "Cảnh báo lũ quét cấp 4", playedAt: "22:46 17/07/2026", duration: "00:34", text: "Cảnh báo lũ quét cấp 4 tại xã Sín Thầu. Người dân chủ động rời xa khu vực ven suối và làm theo hướng dẫn của chính quyền địa phương." },
  { id: "broadcast-002", speakerId: "sp-03", title: "Thông báo sương mù", playedAt: "21:20 17/07/2026", duration: "00:27", text: "Thông báo sương mù dày tại xã Quảng Lâm. Người dân hạn chế di chuyển qua các đoạn đường đèo vào sáng sớm." },
  { id: "broadcast-003", speakerId: "sp-02", title: "Cảnh báo mưa lớn cấp 2", playedAt: "22:58 17/07/2026", duration: "00:31", text: "Cảnh báo mưa lớn cấp 2 tại xã Nậm Kè. Người dân chủ động kiểm tra đường tràn và khu vực có nguy cơ sạt lở." },
];

export function AdminConsole({ page, alertId, sosId }: { page: AdminPage; alertId?: string; sosId?: string }) {
  const { authState, token, admin, authenticate, logout } = useAdminSession();
  const [scope, setScope] = useState<AdminCommune[]>([]); const [risks, setRisks] = useState<CommuneRisk[]>([]); const [incidents, setIncidents] = useState<DeliveryIncident[]>([]); const [alerts, setAlerts] = useState<AdminAlert[]>([]); const [speakers, setSpeakers] = useState<Speaker[]>([]); const [sos,setSos]=useState<SOSRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [menuOpen, setMenuOpen] = useState(false); const [selected, setSelected] = useState<DeliveryIncident>(); const [recipients, setRecipients] = useState<UnreachedRecipients>();
  const dialogRef = useRef<HTMLDivElement>(null);
  const load = useCallback(async (activeToken?: string, signal?: AbortSignal) => {
    setLoading(true);
    setError(undefined);
    const isOverview = page === "overview";
    try {
      const [nextScope, nextRisks, nextIncidents, nextAlerts, nextSpeakers, nextSos] = await Promise.all([
        getAdminCommunes(activeToken, signal),
        isOverview || page === "alerts" ? getScopedRisks(activeToken, signal) : Promise.resolve([]),
        isOverview || page === "delivery" ? getDeliveryIncidents(activeToken, signal) : Promise.resolve([]),
        isOverview || page === "alerts" || page === "delivery" ? getAlerts(activeToken, signal) : Promise.resolve([]),
        isOverview || page === "speakers" ? getSpeakers() : Promise.resolve([]),
        isOverview || (page === "sos" && !sosId) ? getSos(activeToken, signal) : Promise.resolve([]),
      ]);
      if (signal?.aborted) return;
      setScope(nextScope); setRisks(nextRisks); setIncidents(nextIncidents); setAlerts(nextAlerts); setSpeakers(nextSpeakers); setSos(nextSos);
    } catch (reason) {
      if (!signal?.aborted) setError(reason instanceof Error ? reason.message : "Không thể tải dữ liệu điều hành.");
    } finally {
      if (!signal?.aborted) setLoading(false);
    }
  }, [page, sosId]);
  useEffect(() => {
    if (authState !== "authenticated" || !token) return;
    const controller = new AbortController();
    void load(token, controller.signal);
    return () => controller.abort();
  }, [authState, load, token]);
  useEffect(() => { if (!selected) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(undefined); if (event.key === "Tab" && dialogRef.current) { const focusable = [...dialogRef.current.querySelectorAll<HTMLElement>("button,a,[tabindex]:not([tabindex='-1'])")]; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; window.addEventListener("keydown", onKey); dialogRef.current?.querySelector<HTMLElement>("button")?.focus(); return () => window.removeEventListener("keydown", onKey); }, [selected]);
  const highestAlert = useMemo(() => alerts.reduce<AdminAlert | undefined>((highest, alert) => alert.status === "pending_approval" && (!highest || alert.event.risk_level > highest.event.risk_level) ? alert : highest, undefined), [alerts]);
  const onlineSpeakers = useMemo(() => speakers.filter((speaker) => speaker.status === "ONLINE").length, [speakers]);
  const sentToday = useMemo(() => alerts.reduce((sum, alert) => sum + alert.dispatches.reduce((count, dispatch) => count + dispatch.delivered, 0), 0), [alerts]);
  async function openIncident(incident: DeliveryIncident) { setSelected(incident); setRecipients(undefined); try { setRecipients(await getUnreachedRecipients(incident.alertId, token)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tải người chưa nhận."); } }
  async function contact(recipientId: string) { if (!selected) return; await markRecipientContacted(recipientId, token); setRecipients((value) => value ? { ...value, unreachedCount: Math.max(0, value.unreachedCount - 1), deliveredCount: value.deliveredCount + 1, recipients: value.recipients.filter((item) => item.id !== recipientId) } : value); setNotice("Đã ghi nhận liên hệ trực tiếp."); }
  async function retry(id: string) { await retryAlert(id, token); setNotice("Đã gửi lại các kênh lỗi."); }
  if (authState === "checking") return <AdminSessionLoader />;
  if (authState === "unauthenticated") return <AdminLoginGate onAuthenticate={authenticate} />;
  return <main className="admin-console"><header className="admin-public-header"><Link className="admin-public-brand" href="/" aria-label="Về bản đồ cảnh báo thiên tai"><Image src="/figma/dien-bien-science-logo.png" width={99} height={99} priority alt="Biểu trưng Sở Khoa học và Công nghệ Điện Biên" /><span><small>Sở Khoa học &amp; Công nghệ Điện Biên</small><strong>Cảnh báo thiên tai tỉnh Điện Biên</strong></span></Link><nav className="admin-public-nav" aria-label="Điều hướng hệ thống"><Link href="/">Bản đồ cảnh báo</Link><span aria-current="page">Điều hành PCTT</span></nav></header><aside className={`admin-nav ${menuOpen ? "is-open" : ""}`} aria-label="Điều hướng quản trị"><div className="nav-brand"><ShieldCheck size={22} /><span>Điều hành PCTT</span><button aria-label="Đóng menu" onClick={() => setMenuOpen(false)}><X size={20} /></button></div><nav>{nav.map((item) => { const Icon = item.icon; return <Link key={item.page} href={item.href} className={page === item.page ? "active" : ""} onClick={() => setMenuOpen(false)}><Icon size={18} />{item.label}</Link>; })}</nav><div className="nav-session"><span>{admin?.full_name}</span><button onClick={logout}><LogOut size={16} /> Đăng xuất</button></div></aside><div className="console-backdrop" hidden={!menuOpen} onClick={() => setMenuOpen(false)} />
    <section className="console-main"><header className="console-header"><button className="menu-toggle" aria-label="Mở menu" onClick={() => setMenuOpen(true)}><Menu size={22} /></button><div><h1>{page === "overview" ? "Bảng điều hành PCTT" : nav.find((item) => item.page === page)?.label ?? "Admin"}</h1></div></header>
      {notice && <div className="console-notice" role="status" aria-live="polite">{notice}</div>}{error && <div className="console-error" role="alert">{error}<button onClick={() => void load(token)}>Thử lại</button></div>}
      {loading ? <ConsoleSkeleton /> : scope.length === 0 ? <EmptyScope /> : <PageContent page={page} alertId={alertId} sosId={sosId} scope={scope} risks={risks} incidents={incidents} alerts={alerts} speakers={speakers} sos={sos} highestAlert={highestAlert} onlineSpeakers={onlineSpeakers} sentToday={sentToday} onProcess={openIncident} onRetry={retry} token={token} />}
    </section>{selected && <ContactDrawer incident={selected} recipients={recipients} alert={alerts.find((item) => item.id === selected.alertId)} onClose={() => setSelected(undefined)} onContact={contact} onRetry={retry} dialogRef={dialogRef} />}</main>;
}

function AdminSessionLoader() {
  return <main className="admin-console admin-login-shell"><header className="admin-public-header"><Link className="admin-public-brand" href="/" aria-label="Về bản đồ cảnh báo thiên tai"><Image src="/figma/dien-bien-science-logo.png" width={99} height={99} priority alt="Biểu trưng Sở Khoa học và Công nghệ Điện Biên" /><span><small>Sở Khoa học &amp; Công nghệ Điện Biên</small><strong>Cảnh báo thiên tai tỉnh Điện Biên</strong></span></Link><nav className="admin-public-nav" aria-label="Điều hướng hệ thống"><Link href="/">Bản đồ cảnh báo</Link><span aria-current="page">Điều hành PCTT</span></nav></header><section className="admin-session-loader" role="status" aria-live="polite"><ShieldCheck size={30} /><strong>Đang mở Điều hành PCTT…</strong><span>Kiểm tra phiên đăng nhập an toàn.</span></section></main>;
}

function AdminLoginGate({ onAuthenticate }: { onAuthenticate: (email: string, password: string) => Promise<void> }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setError(undefined); try { await onAuthenticate(email.trim(), password); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đăng nhập. Vui lòng thử lại."); } finally { setSubmitting(false); } }
  return <main className="admin-console admin-login-shell"><header className="admin-public-header"><Link className="admin-public-brand" href="/" aria-label="Về bản đồ cảnh báo thiên tai"><Image src="/figma/dien-bien-science-logo.png" width={99} height={99} priority alt="Biểu trưng Sở Khoa học và Công nghệ Điện Biên" /><span><small>Sở Khoa học &amp; Công nghệ Điện Biên</small><strong>Cảnh báo thiên tai tỉnh Điện Biên</strong></span></Link><nav className="admin-public-nav" aria-label="Điều hướng hệ thống"><Link href="/">Bản đồ cảnh báo</Link><span aria-current="page">Điều hành PCTT</span></nav></header><section className="admin-login-card" aria-labelledby="admin-login-title"><div className="admin-login-mark"><ShieldCheck size={28} /></div><h1 id="admin-login-title">Đăng nhập</h1><form onSubmit={(event) => void submit(event)}><label>Email cán bộ<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="username" required placeholder="ten.canbo@dienbien.gov.vn" /></label><label>Mật khẩu<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required minLength={6} /></label>{error && <p className="admin-login-error" role="alert">{error}</p>}<button className="primary-button" type="submit" disabled={submitting}>{submitting ? "Đang đăng nhập…" : "Đăng nhập điều hành"}</button></form><Link href="/">Quay lại bản đồ cảnh báo</Link></section></main>;
}

function PageContent(props: { page: AdminPage; alertId?: string;sosId?:string; scope: AdminCommune[]; risks: CommuneRisk[]; incidents: DeliveryIncident[]; alerts: AdminAlert[]; speakers:Speaker[]; sos:SOSRequest[]; highestAlert?: AdminAlert; onlineSpeakers: number; sentToday: number; onProcess: (incident: DeliveryIncident) => void; onRetry: (id: string) => void;token?:string }) {
  const { page } = props; if (page === "overview") return <Overview {...props} />; if (page === "alerts") return props.alertId ? <AlertDetail alert={props.alerts.find((item) => item.id === props.alertId)} onRetry={props.onRetry} /> : <Alerts alerts={props.alerts} risks={props.risks} />; if (page === "delivery") return <Delivery incidents={props.incidents} onProcess={props.onProcess} />; if(page==="sos")return <SosPage items={props.sos} detailId={props.sosId} token={props.token}/>; if (page === "speakers") return <Speakers items={props.speakers} />; return <Audit />;
}
function Overview({ scope, risks, incidents, alerts, sos, highestAlert, onlineSpeakers, sentToday, onProcess }: Parameters<typeof PageContent>[0]) { const urgent=sos.filter(x=>x.status==="NEW"); return <><section className="overview-metrics"><Metric label="Cảnh báo đang hiệu lực" value={alerts.filter((item) => ["pending_approval", "partial_failed"].includes(item.status)).length} tone="critical" /><Metric label="Xã có nguy cơ" value={risks.filter((item) => item.risk_level > 0).length} suffix={`/${scope.length}`} tone="warning" /><Metric label="SOS chờ xử lý" value={urgent.length} tone="critical" /><Metric label="Loa trực tuyến" value={onlineSpeakers} suffix="/3" tone="safe" /><Metric label="Tin gửi hôm nay" value={sentToday} /></section>{highestAlert ? <section className="priority-alert"><div><span>Cao nhất cần phê duyệt · Cấp {highestAlert.event.risk_level}</span><h2>{highestAlert.bulletins[0]?.title ?? hazardLabel(highestAlert.event.hazard)}</h2><p>{highestAlert.event.commune_name} · phát hành {formatDate(highestAlert.created_at)}</p></div><Link className="primary-link" href={`/admin/alerts/${highestAlert.id}`}>Xem và phê duyệt <ChevronRight size={17} /></Link></section> : <section className="console-empty"><ShieldCheck size={26} /><h2>Không có cảnh báo chờ phê duyệt</h2><p>Hệ thống đang theo dõi các xã trong phạm vi được phân quyền.</p></section>}{urgent.length>0&&<section className="console-card sos-summary"><header><h2><span>SOS</span> mới hoặc nghiêm trọng</h2><Link href="/admin/sos">Xem tất cả SOS</Link></header><SosRows items={urgent.slice(0,3)}/></section>}<div className="overview-grid overview-grid--single"><section className="console-card contact-panel"><header><h2>Cần liên hệ trực tiếp</h2><Link href="/admin/delivery">Xem tất cả</Link></header><IncidentRows incidents={incidents.slice(0, 3)} onProcess={onProcess} /></section></div></> }
function Metric({ label, value, suffix, tone = "default" }: { label: string; value: number; suffix?: string; tone?: string }) { return <article className={`console-metric ${tone}`}><p>{label}</p><strong>{value}<small>{suffix}</small></strong></article>; }
function RiskRows({ risks }: { risks: CommuneRisk[] }) { return risks.length ? <ul className="risk-rows">{risks.map((risk) => <li key={risk.code}><i style={{ background: risk.risk_color }} /><strong>{risk.name}</strong><span>{risk.top_hazard_label ?? risk.risk_label} · cấp {risk.risk_level}</span></li>)}</ul> : <p className="quiet">Không có nguy cơ đang hiệu lực.</p>; }
function IncidentRows({ incidents, onProcess }: { incidents: DeliveryIncident[]; onProcess: (item: DeliveryIncident) => void }) { return incidents.length ? <ul className="incident-rows">{incidents.map((item) => <li key={item.alertId}><div><strong>{item.alertTitle} · {item.communeName}</strong><span>Cấp {item.level} · {item.unreachedCount} người chưa nhận</span></div><button onClick={() => onProcess(item)}>Xử lý</button></li>)}</ul> : <p className="quiet">Không có sự cố gửi tin cần xử lý.</p>; }
function SosRows({items}:{items:SOSRequest[]}){return <ul className="incident-rows">{items.map(item=><li key={item.id}><div><strong><span className="sos-label">SOS</span> · {item.communeName??"Chưa xác định xã"}</strong><span>{item.peopleCount} người · {sosStatusLabel(item.status)} · {formatDate(item.createdAt)}</span></div><Link className="outline-button" href={`/admin/sos/${item.id}`}>Xem</Link></li>)}</ul>}
function SosPage({items,detailId,token}:{items:SOSRequest[];detailId?:string;token?:string}){const [query,setQuery]=useState("");const [detail,setDetail]=useState<SOSRequest|undefined>(detailId?items.find(x=>x.id===detailId):undefined);const [notice,setNotice]=useState("");useEffect(()=>{if(detailId)void getSosDetail(detailId,token).then(setDetail)},[detailId,token]);async function transition(status:SOSStatus){if(!detail||!confirm(`Chuyển SOS sang ${status}?`))return;try{await updateSosStatus(detail.id,status,token);setDetail({...detail,status});setNotice("Đã cập nhật trạng thái và ghi audit log.")}catch{setNotice("Không thể cập nhật trạng thái SOS.")}}if(detailId){if(!detail)return <ConsoleSkeleton/>;const action=detail.status==="NEW"?{label:"Xác nhận tiếp nhận",next:"ACKNOWLEDGED" as const}:detail.status==="ACKNOWLEDGED"?{label:"Bắt đầu điều phối",next:"DISPATCHED" as const}:detail.status==="DISPATCHED"?{label:"Đã cứu trợ",next:"RESCUED" as const}:undefined;return <section className="detail-card sos-detail" aria-live="polite"><div className="sos-detail-status"><span className="level-dot level-3">SOS · {detail.status}</span>{detail.isDemo&&<p className="demo-warning">Dữ liệu demo — không sử dụng để điều phối thực tế.</p>}</div><div className="sos-detail-hero"><div><p className="sos-detail-kicker">Yêu cầu cứu hộ</p><h2>{detail.communeName??"Chưa xác định xã"}</h2><p>{detail.description}</p></div></div><dl className="sos-facts"><div><dt>Tọa độ hiện trường</dt><dd>{detail.latitude}, {detail.longitude}</dd></div><div><dt>Người cần cứu</dt><dd>{detail.peopleCount}</dd></div><div><dt>Trạng thái định vị</dt><dd>{detail.mappingStatus}</dd></div></dl><div className="sos-detail-actions"><a className="outline-button" href={createGoogleMapsDirectionsUrl(detail.latitude,detail.longitude)} target="_blank" rel="noopener noreferrer" aria-label={`Chỉ đường Google Maps đến ${detail.communeName??detail.id}`}><Navigation size={16}/> Mở chỉ đường <ExternalLink size={14}/></a>{action&&<button className="primary-button" onClick={()=>void transition(action.next)}>{action.label}</button>}</div><section className="sos-audit" aria-labelledby="sos-audit-heading"><div><p className="sos-detail-kicker">Theo dõi xử lý</p><h3 id="sos-audit-heading">Nhật ký điều phối</h3></div><ul className="simple-list">{detail.audit?.map((a,i)=><li key={i}><FileCheck2 size={17}/><div><strong>{a.step}</strong><small>{a.detail}</small></div></li>)}</ul></section>{notice&&<p className="console-notice">{notice}</p>}</section>}const shown=items.filter(item=>`${item.id} ${item.communeName??""} ${item.description}`.toLowerCase().includes(query.toLowerCase()));return <section className="console-card"><header><h2>SOS khẩn cấp</h2><span>{items.filter(x=>x.status==="NEW").length} mới</span></header><label className="delivery-search">Tìm SOS<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Mã SOS, xã hoặc nội dung"/></label><SosRows items={shown}/></section>}
function Alerts({ alerts, risks }: { alerts: AdminAlert[]; risks: CommuneRisk[] }) { const searchParams = useSearchParams(); const risksActive = searchParams.get("tab") === "risks"; return <section className="console-card"><header><h2>Cảnh báo &amp; nguy cơ</h2><span>{risksActive ? `${risks.length} xã trong phạm vi` : `${alerts.length} cảnh báo trong phạm vi`}</span></header><div className="tabs" role="tablist" aria-label="Nội dung cảnh báo"><Link href="/admin/alerts" role="tab" aria-selected={!risksActive} className={!risksActive ? "active" : ""}>Cảnh báo</Link><Link href="/admin/alerts?tab=risks" role="tab" aria-selected={risksActive} className={risksActive ? "active" : ""}>Nguy cơ theo xã</Link></div>{risksActive ? <RiskRows risks={[...risks].sort((a, b) => b.risk_level - a.risk_level)} /> : <div className="alert-list">{alerts.map((alert) => <Link href={`/admin/alerts/${alert.id}`} key={alert.id}><span className={`level-dot level-${alert.event.risk_level}`}>Cấp {alert.event.risk_level}</span><div><strong>{alert.bulletins[0]?.title ?? hazardLabel(alert.event.hazard)}</strong><small>{alert.event.commune_name} · {formatDate(alert.created_at)}</small></div><span>{alertStatusLabel(alert.status)}</span><ChevronRight size={18} /></Link>)}</div>}</section> }
function AlertDetail({ alert, onRetry }: { alert?: AdminAlert; onRetry: (id: string) => void }) { return !alert ? <section className="console-empty"><h2>Không tìm thấy cảnh báo</h2><Link href="/admin/alerts">Quay lại danh sách cảnh báo</Link></section> : <section className="detail-card"><span className={`level-dot level-${alert.event.risk_level}`}>Cấp {alert.event.risk_level}</span><h2>{alert.bulletins[0]?.title}</h2><p>{alert.bulletins[0]?.body}</p><dl><div><dt>Xã</dt><dd>{alert.event.commune_name}</dd></div><div><dt>Phát hành</dt><dd>{formatDate(alert.created_at)}</dd></div><div><dt>Trạng thái</dt><dd>{alertStatusLabel(alert.status)}</dd></div></dl><button className="primary-button" onClick={() => onRetry(alert.id)}><RefreshCw size={16} /> Gửi lại kênh lỗi</button></section> }
function Delivery({ incidents, onProcess }: { incidents: DeliveryIncident[]; onProcess: (item: DeliveryIncident) => void }) { const [tab, setTab] = useState("Cần liên hệ"); const [query, setQuery] = useState(""); const shown = incidents.filter((item) => `${item.alertTitle} ${item.communeName}`.toLowerCase().includes(query.toLowerCase())); return <section className="console-card delivery-page"><header><h2>Gửi tin và sự cố</h2></header><div className="tabs" role="tablist">{["Cần liên hệ", "Lịch sử gửi"].map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Cần liên hệ" ? <><label className="delivery-search">Tìm cảnh báo hoặc xã<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ví dụ: Sín Thầu" /></label><IncidentRows incidents={shown} onProcess={onProcess} /></> : <p className="quiet">{tab} được tổng hợp từ nhật ký dispatch của từng cảnh báo.</p>}</section> }
function Speakers({ items }: { items: Speaker[] }) { const [playingId, setPlayingId] = useState<string>(); useEffect(() => () => window.speechSynthesis?.cancel(), []); function togglePlayback(item: typeof speakerBroadcasts[number]) { if (!("speechSynthesis" in window)) return; if (playingId === item.id) { window.speechSynthesis.cancel(); setPlayingId(undefined); return; } window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(item.text); utterance.lang = "vi-VN"; utterance.rate = .94; utterance.onend = () => setPlayingId((active) => active === item.id ? undefined : active); utterance.onerror = () => setPlayingId((active) => active === item.id ? undefined : active); setPlayingId(item.id); window.speechSynthesis.speak(utterance); } const broadcasts = speakerBroadcasts.map((broadcast) => ({ ...broadcast, speaker: items.find((item) => item.id === broadcast.speakerId) })).filter((broadcast) => broadcast.speaker); return <section className="console-card speaker-broadcasts"><header><div><h2>Âm thanh đã phát</h2><p className="quiet">Nghe lại các bản tin đã được gửi tới loa truyền thanh.</p></div><span>{broadcasts.length} bản tin</span></header><ul className="broadcast-list">{broadcasts.map((broadcast) => <li key={broadcast.id}><Volume2 size={19} /><div><strong>{broadcast.title}</strong><small>{broadcast.speaker?.name} · {broadcast.speaker?.communeName}</small><span>{broadcast.playedAt} · {broadcast.duration}</span></div><button type="button" className={playingId === broadcast.id ? "is-playing" : ""} onClick={() => togglePlayback(broadcast)} aria-pressed={playingId === broadcast.id} aria-label={`${playingId === broadcast.id ? "Dừng" : "Nghe lại"} ${broadcast.title}`}>{playingId === broadcast.id ? <><Square size={15} /> Dừng</> : <><Play size={15} /> Nghe lại</>}</button></li>)}</ul></section> }
function Audit() { const [items, setItems] = useState<AuditEntry[]>([]); const [selected, setSelected] = useState<AuditEntry>(); useEffect(() => { void getAuditEntries().then(setItems); }, []); return <section className="console-card audit-card"><header><h2>Nhật ký tương tác</h2><FileCheck2 size={19} /></header><ul className="audit-list">{items.map((item) => { const isOpen = selected?.id === item.id; const history = item.history ?? [{ occurredAt: item.occurredAt, detail: item.detail, actor: item.actor }]; return <li key={item.id}><button type="button" onClick={() => setSelected(isOpen ? undefined : item)} aria-expanded={isOpen} aria-controls={`audit-history-${item.id}`}><BellRing size={18} /><span><strong>{item.action}</strong><small>{item.detail} · {item.actor}</small></span><time>{item.occurredAt}</time><ChevronRight size={18} /></button>{isOpen && <section className="audit-history" id={`audit-history-${item.id}`} aria-live="polite"><header><div><p>Lịch sử sự kiện</p><h3>{item.action}</h3></div><button type="button" onClick={() => setSelected(undefined)} aria-label="Đóng lịch sử"><X size={18} /></button></header><ol>{history.map((event, index) => <li key={`${event.occurredAt}-${index}`}><time>{event.occurredAt}</time><div><strong>{event.detail}</strong><small>{event.actor}</small></div></li>)}</ol></section>}</li>; })}</ul></section> }
function ContactDrawer({ incident, recipients, alert, onClose, onContact, onRetry, dialogRef }: { incident: DeliveryIncident; recipients?: UnreachedRecipients; alert?: AdminAlert; onClose: () => void; onContact: (id: string) => void; onRetry: (id: string) => void; dialogRef: RefObject<HTMLDivElement | null> }) { return <div className="drawer-backdrop" role="presentation"><div className="contact-drawer" role="dialog" aria-modal="true" aria-labelledby="contact-title" ref={dialogRef}><header><div><p>Cần liên hệ trực tiếp</p><h2 id="contact-title">{alert?.bulletins[0]?.title ?? incident.alertTitle}</h2><span>{incident.communeName} · Cấp {incident.level}</span></div><button aria-label="Đóng" onClick={onClose}><X size={20} /></button></header><div className="delivery-progress"><strong>{recipients?.deliveredCount ?? incident.deliveredCount}/{recipients?.targetedCount ?? incident.targetedCount}</strong><span>đã nhận</span></div>{!recipients ? <p className="quiet">Đang tải danh sách người chưa nhận…</p> : recipients.recipients.length === 0 ? <div className="console-empty"><ShieldCheck size={24} /><h3>Không còn người chờ liên hệ trực tiếp.</h3></div> : <ul className="recipient-drawer-list">{recipients.recipients.map((item) => <li key={item.id}><div><strong>{item.fullName}</strong><small>{item.address} · {item.phoneMasked ?? "Số điện thoại chưa có"}</small><span>{item.channel} · {item.reason}</span></div><button onClick={() => void onContact(item.id)}>Đã liên hệ</button></li>)}</ul>}<footer><button className="outline-button" onClick={() => void onRetry(incident.alertId)}><RefreshCw size={16} /> Gửi lại tất cả</button><button className="primary-button" onClick={() => void onRetry(incident.alertId)}><UsersRound size={16} /> Gửi danh sách trưởng bản</button><Link href={`/admin/alerts/${incident.alertId}`} onClick={onClose}>Mở chi tiết cảnh báo</Link></footer></div></div> }
function ConsoleSkeleton() { return <div className="console-skeleton" aria-label="Đang tải dữ liệu"><i /><i /><i /><i /><i /></div> }
function EmptyScope() { return <section className="console-empty"><UsersRound size={28} /><h2>Chưa được gán phạm vi xã</h2><p>Liên hệ quản trị viên để được cấp quyền trước khi xem dữ liệu điều hành.</p></section> }
