"use client";

import Link from "next/link";
import { type RefObject, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, BellRing, ChevronRight, ClipboardList, CloudRain, ExternalLink, FileCheck2, Map, Menu, Navigation, Radio, RefreshCw, Send, ShieldCheck, Siren, UsersRound, Volume2, X } from "lucide-react";
import { connectDemoSession } from "@/services/adminApi";
import { getAdminCommunes } from "@/services/admin-scope-service";
import { getAuditEntries, getAlerts, getDeliveryIncidents, getSpeakers, getUnreachedRecipients, markRecipientContacted, retryAlert } from "@/services/delivery-service";
import { getScopedRisks } from "@/services/risk-service";
import { useMocks } from "@/services/adminClient";
import type { AdminAlert, AdminCommune, CommuneRisk, DeliveryIncident, Speaker, UnreachedRecipients } from "@/types/admin-console";
import type { SOSRequest, SOSStatus } from "@/types/sos";
import { createGoogleMapsDirectionsUrl, getSos, getSosDetail, updateSosStatus } from "@/services/sos-service";

export type AdminPage = "overview" | "alerts" | "risks" | "delivery" | "sos" | "speakers" | "audit";
const tokenKey = "dien-bien-admin-token";
const nav: Array<{ page: AdminPage; href: string; label: string; icon: typeof Map }> = [{ page: "overview", href: "/admin", label: "Tổng quan", icon: Map }, { page: "alerts", href: "/admin/alerts", label: "Cảnh báo", icon: AlertTriangle }, { page: "risks", href: "/admin/risks", label: "Nguy cơ theo xã", icon: CloudRain }, { page: "delivery", href: "/admin/delivery", label: "Gửi tin & sự cố", icon: Send }, { page: "sos", href: "/admin/sos", label: "SOS khẩn cấp", icon: Siren }, { page: "speakers", href: "/admin/speakers", label: "Loa truyền thanh", icon: Volume2 }, { page: "audit", href: "/admin/audit", label: "Nhật ký kiểm toán", icon: ClipboardList }];
const formatDate = (value: string) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
const hazardLabel = (hazard: string) => ({ flash_flood: "Lũ quét", heavy_rain: "Mưa lớn", fog: "Sương mù", landslide: "Sạt lở" }[hazard.toLowerCase()] ?? hazard);

export function AdminConsole({ page, alertId, sosId }: { page: AdminPage; alertId?: string; sosId?: string }) {
  const [token, setToken] = useState<string>(); const [scope, setScope] = useState<AdminCommune[]>([]); const [risks, setRisks] = useState<CommuneRisk[]>([]); const [incidents, setIncidents] = useState<DeliveryIncident[]>([]); const [alerts, setAlerts] = useState<AdminAlert[]>([]); const [speakers, setSpeakers] = useState<Speaker[]>([]); const [sos,setSos]=useState<SOSRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [menuOpen, setMenuOpen] = useState(false); const [selected, setSelected] = useState<DeliveryIncident>(); const [recipients, setRecipients] = useState<UnreachedRecipients>();
  const dialogRef = useRef<HTMLDivElement>(null);
  const load = useCallback(async (activeToken?: string, signal?: AbortSignal) => {
    setLoading(true);
    setError(undefined);
    const isOverview = page === "overview";
    try {
      const [nextScope, nextRisks, nextIncidents, nextAlerts, nextSpeakers, nextSos] = await Promise.all([
        getAdminCommunes(activeToken, signal),
        isOverview || page === "risks" ? getScopedRisks(activeToken, signal) : Promise.resolve([]),
        isOverview || page === "delivery" ? getDeliveryIncidents(activeToken, signal) : Promise.resolve([]),
        isOverview || page === "alerts" || page === "delivery" ? getAlerts(activeToken, signal) : Promise.resolve([]),
        isOverview || page === "speakers" ? getSpeakers() : Promise.resolve([]),
        isOverview || (page === "sos" && !sosId) ? getSos(activeToken, signal) : Promise.resolve([]),
      ]);
      if (signal?.aborted) return;
      setScope(nextScope); setRisks(nextRisks); setIncidents(nextIncidents); setAlerts(nextAlerts); setSpeakers(nextSpeakers); setSos(nextSos);
    } catch (reason) {
      if (!signal?.aborted) setError(reason instanceof Error ? reason.message : "Không thể tải dữ liệu điều hành.");
    } finally {
      if (!signal?.aborted) setLoading(false);
    }
  }, [page, sosId]);
  useEffect(() => {
    const controller = new AbortController();
    const saved = window.sessionStorage.getItem(tokenKey) ?? undefined;
    setToken(saved);
    void load(saved, controller.signal);
    return () => controller.abort();
  }, [load]);
  useEffect(() => { if (!selected) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(undefined); if (event.key === "Tab" && dialogRef.current) { const focusable = [...dialogRef.current.querySelectorAll<HTMLElement>("button,a,[tabindex]:not([tabindex='-1'])")]; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; window.addEventListener("keydown", onKey); dialogRef.current?.querySelector<HTMLElement>("button")?.focus(); return () => window.removeEventListener("keydown", onKey); }, [selected]);
  const highestAlert = useMemo(() => alerts.reduce<AdminAlert | undefined>((highest, alert) => alert.status === "pending_approval" && (!highest || alert.event.risk_level > highest.event.risk_level) ? alert : highest, undefined), [alerts]);
  const onlineSpeakers = useMemo(() => speakers.filter((speaker) => speaker.status === "ONLINE").length, [speakers]);
  const sentToday = useMemo(() => alerts.reduce((sum, alert) => sum + alert.dispatches.reduce((count, dispatch) => count + dispatch.delivered, 0), 0), [alerts]);
  async function connect() { try { const next = await connectDemoSession(); window.sessionStorage.setItem(tokenKey, next); setToken(next); await load(next); setNotice("Đã kết nối tài khoản demo."); } catch { setError("Không thể kết nối tài khoản demo."); } }
  async function openIncident(incident: DeliveryIncident) { setSelected(incident); setRecipients(undefined); try { setRecipients(await getUnreachedRecipients(incident.alertId, token)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tải người chưa nhận."); } }
  async function contact(recipientId: string) { if (!selected) return; await markRecipientContacted(recipientId, token); setRecipients((value) => value ? { ...value, unreachedCount: Math.max(0, value.unreachedCount - 1), deliveredCount: value.deliveredCount + 1, recipients: value.recipients.filter((item) => item.id !== recipientId) } : value); setNotice("Đã ghi nhận liên hệ trực tiếp."); }
  async function retry(id: string) { await retryAlert(id, token); setNotice("Đã gửi lại các kênh lỗi."); }
  const title = nav.find((item) => item.page === page)?.label ?? "Admin";
  return <main className="admin-console"><aside className={`admin-nav ${menuOpen ? "is-open" : ""}`} aria-label="Điều hướng quản trị"><div className="nav-brand"><ShieldCheck size={22} /><span>Điều hành PCTT</span><button aria-label="Đóng menu" onClick={() => setMenuOpen(false)}><X size={20} /></button></div><nav>{nav.map((item) => { const Icon = item.icon; return <Link key={item.page} href={item.href} className={page === item.page ? "active" : ""} onClick={() => setMenuOpen(false)}><Icon size={18} />{item.label}</Link>; })}</nav><div className="nav-scope"><Map size={16} /><span>Phạm vi: <strong>{scope.length} xã</strong></span></div></aside><div className="console-backdrop" hidden={!menuOpen} onClick={() => setMenuOpen(false)} />
    <section className="console-main"><header className="console-header"><button className="menu-toggle" aria-label="Mở menu" onClick={() => setMenuOpen(true)}><Menu size={22} /></button><div><p className="console-eyebrow">ĐIỀU HÀNH CẢNH BÁO SỚM</p><div className="breadcrumbs"><Link href="/admin">Tổng quan</Link>{page !== "overview" && <><ChevronRight size={14} /><span>{title}</span></>}</div><h1>{page === "overview" ? "Bảng điều hành PCTT" : title}</h1></div><div className="console-actions"><span className="scope-badge"><Map size={15} /> Phạm vi: {scope.length} xã</span><span className="mode-badge">{useMocks ? "Dữ liệu demo" : "Dữ liệu trực tiếp"}</span><button className="outline-button" onClick={() => void load(token)} disabled={loading}><RefreshCw size={16} /> Làm mới</button>{!token && !useMocks && <button className="outline-button" onClick={() => void connect()}>Kết nối demo</button>}</div></header>
      {notice && <div className="console-notice" role="status" aria-live="polite">{notice}</div>}{error && <div className="console-error" role="alert">{error}<button onClick={() => void load(token)}>Thử lại</button></div>}
      {loading ? <ConsoleSkeleton /> : scope.length === 0 ? <EmptyScope /> : <PageContent page={page} alertId={alertId} sosId={sosId} scope={scope} risks={risks} incidents={incidents} alerts={alerts} speakers={speakers} sos={sos} highestAlert={highestAlert} onlineSpeakers={onlineSpeakers} sentToday={sentToday} onProcess={openIncident} onRetry={retry} token={token} />}
    </section>{selected && <ContactDrawer incident={selected} recipients={recipients} alert={alerts.find((item) => item.id === selected.alertId)} onClose={() => setSelected(undefined)} onContact={contact} onRetry={retry} dialogRef={dialogRef} />}</main>;
}

function PageContent(props: { page: AdminPage; alertId?: string;sosId?:string; scope: AdminCommune[]; risks: CommuneRisk[]; incidents: DeliveryIncident[]; alerts: AdminAlert[]; speakers:Speaker[]; sos:SOSRequest[]; highestAlert?: AdminAlert; onlineSpeakers: number; sentToday: number; onProcess: (incident: DeliveryIncident) => void; onRetry: (id: string) => void;token?:string }) {
  const { page } = props; if (page === "overview") return <Overview {...props} />; if (page === "alerts") return props.alertId ? <AlertDetail alert={props.alerts.find((item) => item.id === props.alertId)} onRetry={props.onRetry} /> : <Alerts alerts={props.alerts} />; if (page === "risks") return <Risks risks={props.risks} />; if (page === "delivery") return <Delivery incidents={props.incidents} onProcess={props.onProcess} />; if(page==="sos")return <SosPage items={props.sos} detailId={props.sosId} token={props.token}/>; if (page === "speakers") return <Speakers items={props.speakers} />; return <Audit />;
}
function Overview({ scope, risks, incidents, alerts, sos, highestAlert, onlineSpeakers, sentToday, onProcess }: Parameters<typeof PageContent>[0]) { const topRisks = [...risks].sort((a, b) => b.risk_level - a.risk_level).slice(0, 4);const urgent=sos.filter(x=>x.status==="NEW"); return <><section className="overview-metrics"><Metric label="Cảnh báo đang hiệu lực" value={alerts.filter((item) => ["pending_approval", "partial_failed"].includes(item.status)).length} tone="critical" /><Metric label="Xã có nguy cơ" value={risks.filter((item) => item.risk_level > 0).length} suffix={`/${scope.length}`} tone="warning" /><Metric label="SOS chờ xử lý" value={urgent.length} tone="critical" /><Metric label="Loa trực tuyến" value={onlineSpeakers} suffix="/3" tone="safe" /><Metric label="Tin gửi hôm nay" value={sentToday} /></section>{urgent.length>0&&<section className="console-card"><header><h2>SOS mới hoặc nghiêm trọng</h2><Link href="/admin/sos">Xem tất cả SOS</Link></header><SosRows items={urgent.slice(0,3)}/></section>}{highestAlert ? <section className="priority-alert"><div><span>Cao nhất cần phê duyệt · Cấp {highestAlert.event.risk_level}</span><h2>{highestAlert.bulletins[0]?.title ?? hazardLabel(highestAlert.event.hazard)}</h2><p>{highestAlert.event.commune_name} · phát hành {formatDate(highestAlert.created_at)}</p></div><Link className="primary-link" href={`/admin/alerts/${highestAlert.id}`}>Xem và phê duyệt <ChevronRight size={17} /></Link></section> : <section className="console-empty"><ShieldCheck size={26} /><h2>Không có cảnh báo chờ phê duyệt</h2><p>Hệ thống đang theo dõi các xã trong phạm vi được phân quyền.</p></section>}<div className="overview-grid"><section className="console-card"><header><h2>Nguy cơ theo xã</h2><Link href="/admin/risks">Xem tất cả</Link></header><RiskRows risks={topRisks} /></section><section className="console-card"><header><h2>Cần liên hệ trực tiếp</h2><Link href="/admin/delivery">Xem tất cả</Link></header><IncidentRows incidents={incidents.slice(0, 3)} onProcess={onProcess} /></section></div></> }
function Metric({ label, value, suffix, tone = "default" }: { label: string; value: number; suffix?: string; tone?: string }) { return <article className={`console-metric ${tone}`}><p>{label}</p><strong>{value}<small>{suffix}</small></strong></article>; }
function RiskRows({ risks }: { risks: CommuneRisk[] }) { return risks.length ? <ul className="risk-rows">{risks.map((risk) => <li key={risk.code}><i style={{ background: risk.risk_color }} /><strong>{risk.name}</strong><span>{risk.top_hazard_label ?? risk.risk_label} · cấp {risk.risk_level}</span></li>)}</ul> : <p className="quiet">Không có nguy cơ đang hiệu lực.</p>; }
function IncidentRows({ incidents, onProcess }: { incidents: DeliveryIncident[]; onProcess: (item: DeliveryIncident) => void }) { return incidents.length ? <ul className="incident-rows">{incidents.map((item) => <li key={item.alertId}><div><strong>{item.alertTitle} · {item.communeName}</strong><span>Cấp {item.level} · {item.unreachedCount} người chưa nhận</span></div><button onClick={() => onProcess(item)}>Xử lý</button></li>)}</ul> : <p className="quiet">Không có sự cố gửi tin cần xử lý.</p>; }
function SosRows({items}:{items:SOSRequest[]}){return <ul className="incident-rows">{items.map(item=><li key={item.id}><div><strong>SOS · {item.communeName??"Chưa xác định xã"}</strong><span>{item.peopleCount} người · {item.status} · {formatDate(item.createdAt)}</span></div><Link className="outline-button" href={`/admin/sos/${item.id}`}>Xem</Link></li>)}</ul>}
function SosPage({items,detailId,token}:{items:SOSRequest[];detailId?:string;token?:string}){const [query,setQuery]=useState("");const [detail,setDetail]=useState<SOSRequest|undefined>(detailId?items.find(x=>x.id===detailId):undefined);const [notice,setNotice]=useState("");useEffect(()=>{if(detailId)void getSosDetail(detailId,token).then(setDetail)},[detailId,token]);async function transition(status:SOSStatus){if(!detail||!confirm(`Chuyển SOS sang ${status}?`))return;try{await updateSosStatus(detail.id,status,token);setDetail({...detail,status});setNotice("Đã cập nhật trạng thái và ghi audit log.")}catch{setNotice("Không thể cập nhật trạng thái SOS.")}}if(detailId)return !detail?<ConsoleSkeleton/>:<section className="detail-card" aria-live="polite"><span className="level-dot level-3">SOS · {detail.status}</span>{detail.isDemo&&<p className="demo-warning">Dữ liệu demo - không sử dụng để điều phối thực tế.</p>}<h2>{detail.communeName??"Chưa xác định xã"}</h2><p>{detail.description}</p><dl><div><dt>Tọa độ</dt><dd>{detail.latitude}, {detail.longitude}</dd></div><div><dt>Người cần cứu</dt><dd>{detail.peopleCount}</dd></div><div><dt>Mapping</dt><dd>{detail.mappingStatus}</dd></div></dl><a className="outline-button" href={createGoogleMapsDirectionsUrl(detail.latitude,detail.longitude)} target="_blank" rel="noopener noreferrer" aria-label={`Chỉ đường Google Maps đến ${detail.communeName??detail.id}`}><Navigation size={16}/> Chỉ đường Google Maps <ExternalLink size={14}/></a><div className="sos-actions">{detail.status==="NEW"&&<button className="primary-button" onClick={()=>void transition("ACKNOWLEDGED")}>Xác nhận</button>}{detail.status==="ACKNOWLEDGED"&&<button className="primary-button" onClick={()=>void transition("DISPATCHED")}>Bắt đầu điều phối</button>}{detail.status==="DISPATCHED"&&<button className="primary-button" onClick={()=>void transition("RESCUED")}>Đã cứu trợ</button>}</div><h3>Audit log</h3><ul className="simple-list">{detail.audit?.map((a,i)=><li key={i}><FileCheck2 size={17}/><div><strong>{a.step}</strong><small>{a.detail}</small></div></li>)}</ul>{notice&&<p className="console-notice">{notice}</p>}</section>;const shown=items.filter(item=>`${item.id} ${item.communeName??""} ${item.description}`.toLowerCase().includes(query.toLowerCase()));return <section className="console-card"><header><div><h2>SOS khẩn cấp</h2><p className="quiet">Dữ liệu vị trí do backend mapping; không dùng Google Maps để suy ra xã.</p></div><span>{items.filter(x=>x.status==="NEW").length} mới</span></header><label className="delivery-search">Tìm SOS<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Mã SOS, xã hoặc nội dung"/></label><SosRows items={shown}/></section>}
function Alerts({ alerts }: { alerts: AdminAlert[] }) { return <section className="console-card"><header><h2>Tất cả cảnh báo</h2><span>{alerts.length} cảnh báo trong phạm vi</span></header><div className="alert-list">{alerts.map((alert) => <Link href={`/admin/alerts/${alert.id}`} key={alert.id}><span className={`level-dot level-${alert.event.risk_level}`}>Cấp {alert.event.risk_level}</span><div><strong>{alert.bulletins[0]?.title ?? hazardLabel(alert.event.hazard)}</strong><small>{alert.event.commune_name} · {formatDate(alert.created_at)}</small></div><span>{alert.status.replace("_", " ")}</span><ChevronRight size={18} /></Link>)}</div></section> }
function AlertDetail({ alert, onRetry }: { alert?: AdminAlert; onRetry: (id: string) => void }) { return !alert ? <section className="console-empty"><h2>Không tìm thấy cảnh báo</h2><Link href="/admin/alerts">Quay lại danh sách cảnh báo</Link></section> : <section className="detail-card"><span className={`level-dot level-${alert.event.risk_level}`}>Cấp {alert.event.risk_level}</span><h2>{alert.bulletins[0]?.title}</h2><p>{alert.bulletins[0]?.body}</p><dl><div><dt>Xã</dt><dd>{alert.event.commune_name}</dd></div><div><dt>Phát hành</dt><dd>{formatDate(alert.created_at)}</dd></div><div><dt>Trạng thái</dt><dd>{alert.status}</dd></div></dl><button className="primary-button" onClick={() => onRetry(alert.id)}><RefreshCw size={16} /> Gửi lại kênh lỗi</button></section> }
function Risks({ risks }: { risks: CommuneRisk[] }) { return <section className="console-card"><header><h2>Nguy cơ tại các xã được phân quyền</h2><span>{risks.length} xã</span></header><RiskRows risks={[...risks].sort((a, b) => b.risk_level - a.risk_level)} /></section> }
function Delivery({ incidents, onProcess }: { incidents: DeliveryIncident[]; onProcess: (item: DeliveryIncident) => void }) { const [tab, setTab] = useState("Cần liên hệ"); const [query, setQuery] = useState(""); const shown = incidents.filter((item) => `${item.alertTitle} ${item.communeName}`.toLowerCase().includes(query.toLowerCase())); return <section className="console-card delivery-page"><header><div><h2>Gửi tin và sự cố</h2><p>Nhóm theo cảnh báo; chỉ mở dữ liệu cá nhân khi xử lý từng cảnh báo.</p></div></header><div className="tabs" role="tablist">{["Tổng quan", "Kênh gửi", "Cần liên hệ", "Lịch sử gửi"].map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Cần liên hệ" ? <><label className="delivery-search">Tìm cảnh báo hoặc xã<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ví dụ: Sín Thầu" /></label><IncidentRows incidents={shown} onProcess={onProcess} /></> : <p className="quiet">{tab} được tổng hợp từ nhật ký dispatch của từng cảnh báo.</p>}</section> }
function Speakers({ items }: { items: Speaker[] }) { return <section className="console-card"><header><h2>Loa truyền thanh</h2><span>{items.filter((item) => item.status === "ONLINE").length} trực tuyến</span></header><ul className="simple-list">{items.map((item) => <li key={item.id}><Radio size={18} /><div><strong>{item.name}</strong><small>{item.communeName} · Lần cuối {item.lastSeen}</small></div><span className={item.status === "ONLINE" ? "status-good" : "status-warning"}>{item.status === "ONLINE" ? "Trực tuyến" : "Ngoại tuyến"}</span></li>)}</ul></section> }
function Audit() { const [items, setItems] = useState<Array<{ id: string; action: string; detail: string; occurredAt: string; actor: string }>>([]); useEffect(() => { void getAuditEntries().then(setItems); }, []); return <section className="console-card"><header><h2>Nhật ký kiểm toán</h2><FileCheck2 size={19} /></header><ul className="simple-list">{items.map((item) => <li key={item.id}><BellRing size={18} /><div><strong>{item.action}</strong><small>{item.detail} · {item.actor}</small></div><time>{item.occurredAt}</time></li>)}</ul></section> }
function ContactDrawer({ incident, recipients, alert, onClose, onContact, onRetry, dialogRef }: { incident: DeliveryIncident; recipients?: UnreachedRecipients; alert?: AdminAlert; onClose: () => void; onContact: (id: string) => void; onRetry: (id: string) => void; dialogRef: RefObject<HTMLDivElement | null> }) { return <div className="drawer-backdrop" role="presentation"><div className="contact-drawer" role="dialog" aria-modal="true" aria-labelledby="contact-title" ref={dialogRef}><header><div><p>Cần liên hệ trực tiếp</p><h2 id="contact-title">{alert?.bulletins[0]?.title ?? incident.alertTitle}</h2><span>{incident.communeName} · Cấp {incident.level}</span></div><button aria-label="Đóng" onClick={onClose}><X size={20} /></button></header><div className="delivery-progress"><strong>{recipients?.deliveredCount ?? incident.deliveredCount}/{recipients?.targetedCount ?? incident.targetedCount}</strong><span>đã nhận</span></div>{!recipients ? <p className="quiet">Đang tải danh sách người chưa nhận…</p> : recipients.recipients.length === 0 ? <div className="console-empty"><ShieldCheck size={24} /><h3>Không còn người chờ liên hệ trực tiếp.</h3></div> : <ul className="recipient-drawer-list">{recipients.recipients.map((item) => <li key={item.id}><div><strong>{item.fullName}</strong><small>{item.address} · {item.phoneMasked ?? "Số điện thoại chưa có"}</small><span>{item.channel} · {item.reason}</span></div><button onClick={() => void onContact(item.id)}>Đã liên hệ</button></li>)}</ul>}<footer><button className="outline-button" onClick={() => void onRetry(incident.alertId)}><RefreshCw size={16} /> Gửi lại tất cả</button><button className="primary-button" onClick={() => void onRetry(incident.alertId)}><UsersRound size={16} /> Gửi danh sách trưởng bản</button><Link href={`/admin/alerts/${incident.alertId}`} onClick={onClose}>Mở chi tiết cảnh báo</Link></footer></div></div> }
function ConsoleSkeleton() { return <div className="console-skeleton" aria-label="Đang tải dữ liệu"><i /><i /><i /><i /><i /></div> }
function EmptyScope() { return <section className="console-empty"><UsersRound size={28} /><h2>Chưa được gán phạm vi xã</h2><p>Liên hệ quản trị viên để được cấp quyền trước khi xem dữ liệu điều hành.</p></section> }
