"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Check, ChevronRight, Clock3, CloudRain, LogIn, Map, Megaphone, RefreshCw, Send, ShieldCheck, TriangleAlert, UsersRound, Volume2, Waves } from "lucide-react";
import { approveAlert, connectDemoSession, loadDashboard, markRecipientContacted, retryAlert, runMuongPonScenario } from "@/services/adminApi";
import { MetricCard } from "@/components/admin/MetricCard";
import { RecipientPanel } from "@/components/admin/RecipientPanel";
import type { AlertRecord, DashboardSnapshot, RiskSummary } from "@/types/admin";

const storageKey = "dien-bien-admin-token";
const formatNumber = (value: number) => new Intl.NumberFormat("vi-VN").format(value);
const riskTone = (level: number) => level >= 3 ? "critical" : level === 2 ? "warning" : "safe";

export function AdminDashboard() {
  const [snapshot, setSnapshot] = useState<DashboardSnapshot | null>(null);
  const [token, setToken] = useState<string | undefined>();
  const [isLoading, setIsLoading] = useState(true);
  const [busyAction, setBusyAction] = useState<"connect" | "scenario" | "approve" | "retry" | "contact" | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async (nextToken?: string) => { setSnapshot(await loadDashboard(nextToken ?? token)); }, [token]);

  useEffect(() => { const savedToken = window.sessionStorage.getItem(storageKey) ?? undefined; setToken(savedToken); void refresh(savedToken).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Không thể kết nối backend.")).finally(() => setIsLoading(false)); }, [refresh]);
  const activeAlert = useMemo<AlertRecord | undefined>(() => snapshot?.alerts.find((alert) => alert.status === "pending_approval" || alert.status === "partial_failed") ?? snapshot?.alerts[0], [snapshot]);
  const risks = useMemo<RiskSummary[]>(() => [...(snapshot?.risks ?? [])].sort((a, b) => b.risk_level - a.risk_level).slice(0, 4), [snapshot]);
  const delivered = activeAlert?.dispatches.reduce((total, dispatch) => total + dispatch.delivered, 0) ?? 0;
  const totalRecipients = activeAlert?.dispatches.reduce((total, dispatch) => total + dispatch.recipients, 0) ?? 0;
  const isBusy = busyAction !== null;
  const highRiskCount = (snapshot?.risks ?? []).filter((risk) => risk.risk_level >= 3).length;

  async function execute(action: NonNullable<typeof busyAction>, task: () => Promise<void>) { setBusyAction(action); setError(null); setMessage(null); try { await task(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Thao tác không hoàn tất."); } finally { setBusyAction(null); } }
  function ensureSession() { return execute("connect", async () => { const nextToken = await connectDemoSession(); window.sessionStorage.setItem(storageKey, nextToken); setToken(nextToken); await refresh(nextToken); setMessage("Đã kết nối tài khoản demo Mường Pồn. Phiên chỉ lưu trong tab này."); }); }
  function createScenario() { return execute("scenario", async () => { const activeToken = token ?? await connectDemoSession(); if (!token) { window.sessionStorage.setItem(storageKey, activeToken); setToken(activeToken); } await runMuongPonScenario(); await refresh(activeToken); setMessage("Đã tạo kịch bản Mường Pồn 25/7: cảnh báo cấp 3 đang chờ phê duyệt."); }); }
  function approve() { if (!activeAlert || !token) return; return execute("approve", async () => { await approveAlert(activeAlert.id, token); await refresh(token); setMessage("Đã phê duyệt và gửi cảnh báo. Hệ thống đã cập nhật nhật ký phân phối."); }); }
  function retry() { if (!activeAlert || !token) return; return execute("retry", async () => { await retryAlert(activeAlert.id, token); await refresh(token); setMessage("Đã gửi lại các kênh lỗi và làm mới danh sách người cần liên hệ."); }); }
  function contactRecipient(id: string) { if (!token) return; return execute("contact", async () => { await markRecipientContacted(id, token); await refresh(token); setMessage("Đã ghi nhận cán bộ liên hệ trực tiếp; người này đã rời danh sách xử lý."); }); }
  if (isLoading) return <main className="admin-shell"><div className="loading-shell"><RefreshCw className="spin" size={24} /><p>Đang đồng bộ bảng điều hành PCTT…</p></div></main>;

  return <main className="admin-shell"><section className="dashboard" aria-labelledby="dashboard-title">
    <header className="dashboard-header"><div><p className="eyebrow">ĐIỀU HÀNH CẢNH BÁO SỚM</p><h1 id="dashboard-title">Bảng điều khiển PCTT — Điện Biên</h1><p className="update-line">Cập nhật trực tiếp từ {snapshot?.health.weather_provider === "openmeteo" ? "Open-Meteo + trạm KTTV" : "nguồn mock nội bộ"} · backend v{snapshot?.health.version}</p></div><div className="header-actions"><span className={`system-pill ${error ? "system-pill--error" : ""}`}><ShieldCheck size={16} /> {error ? "Cần kiểm tra kết nối" : "Hệ thống hoạt động"}</span><button type="button" className="button button--quiet" onClick={() => void refresh()} disabled={isBusy}><RefreshCw size={16} /> Làm mới</button>{!snapshot?.authenticated ? <button type="button" className="button button--quiet" onClick={ensureSession} disabled={isBusy}><LogIn size={16} /> Kết nối demo</button> : <span className="session-label">Phiên demo đã kết nối</span>}</div></header>
    {error && <div className="notice notice--error" role="alert"><TriangleAlert size={18} /> {error}<button type="button" onClick={() => void refresh()}>Thử lại</button></div>}{message && <div className="notice notice--success" role="status"><Check size={18} /> {message}</div>}
    <section className="metrics" aria-label="Tổng quan vận hành"><MetricCard label="Cảnh báo đang hiệu lực" value={String((snapshot?.alerts ?? []).filter((alert) => ["pending_approval", "partial_failed"].includes(alert.status)).length)} tone="critical" icon={AlertTriangle} /><MetricCard label="Xã có nguy cơ" value={String(highRiskCount)} suffix={`/${snapshot?.risks.length ?? 0}`} tone="critical" icon={Map} /><MetricCard label="Loa trực tuyến" value={String(activeAlert?.dispatches.filter((item) => item.channel.toLowerCase().includes("loa") && item.status === "ok").length ?? 0)} suffix="/1" tone="warning" icon={Volume2} /><MetricCard label="Tin đã gửi hôm nay" value={formatNumber(delivered)} suffix={totalRecipients > 0 ? `/${formatNumber(totalRecipients)}` : undefined} icon={Send} /></section>
    {activeAlert ? <section className={`approval-card approval-card--${activeAlert.status}`} aria-labelledby="approval-title"><header className="approval-meta"><span>{activeAlert.status === "pending_approval" ? `Chờ phê duyệt · Cấp ${activeAlert.event.risk_level}` : activeAlert.status === "partial_failed" ? "Cần gửi lại" : "Đã gửi"}</span><p><Waves size={16} /> {activeAlert.event.hazard === "flash_flood" ? "Lũ quét" : activeAlert.event.hazard} — xã {activeAlert.event.commune_name}</p><time><Clock3 size={15} /> {activeAlert.created_at}</time></header><h2 id="approval-title">{activeAlert.bulletins.find((item) => item.lang === "vi")?.title ?? `Cảnh báo ${activeAlert.event.risk_label} tại ${activeAlert.event.commune_name}`}</h2><p className="approval-body">{activeAlert.bulletins.find((item) => item.lang === "vi")?.body ?? "Chưa có nội dung bản tin tiếng Việt."}</p><p className="provenance"><CloudRain size={16} /> Nguồn: {activeAlert.event.provenance.source} · {activeAlert.event.provenance.rule}</p><footer className="approval-actions">{activeAlert.status === "pending_approval" ? <button type="button" className="button button--primary" onClick={approve} disabled={isBusy || !token}><Send size={16} /> {busyAction === "approve" ? "Đang gửi…" : "Phê duyệt và gửi"}</button> : <button type="button" className="button button--primary" onClick={retry} disabled={isBusy || !token}><RefreshCw size={16} /> {busyAction === "retry" ? "Đang gửi lại…" : "Gửi lại kênh lỗi"}</button>}<button type="button" className="button button--quiet" onClick={createScenario} disabled={isBusy}><AlertTriangle size={16} /> Chạy lại kịch bản</button><span className="language-note"><Megaphone size={16} /> Nghe: Tiếng Việt · Thái · Mông</span></footer></section> : <section className="empty-alert" aria-labelledby="empty-alert-title"><div><ShieldCheck size={28} /><h2 id="empty-alert-title">Chưa có cảnh báo cần phê duyệt</h2><p>Dữ liệu nguy cơ vẫn đang được đồng bộ. Chạy kịch bản demo để kiểm thử đầy đủ luồng duyệt và gửi cảnh báo.</p></div><button type="button" className="button button--primary" onClick={createScenario} disabled={isBusy}><AlertTriangle size={16} /> {busyAction === "scenario" ? "Đang tạo…" : "Tạo kịch bản Mường Pồn"}</button></section>}
    <div className="panel-grid"><section className="panel" aria-labelledby="risk-title"><header className="panel-heading"><h2 id="risk-title">Nguy cơ theo xã</h2><span>{snapshot?.risks.length ?? 0} xã/phường</span></header><ul className="risk-list">{risks.map((risk) => <li key={risk.code}><i className={`dot dot--${riskTone(risk.risk_level)}`} /><strong>{risk.name}</strong><span>{risk.top_hazard_label ?? risk.risk_label} · cấp {risk.risk_level}</span></li>)}</ul><Link className="panel-link" href="/"><Map size={17} /> Xem bản đồ đầy đủ <ChevronRight size={17} /></Link></section><section className="panel" aria-labelledby="log-title"><header className="panel-heading"><h2 id="log-title">Nhật ký gửi tin</h2><span>{activeAlert?.dispatches.length ?? 0} kênh</span></header>{activeAlert?.dispatches.length ? <ul className="dispatch-list">{activeAlert.dispatches.map((dispatch, index) => <li key={`${dispatch.channel}-${index}`}><i className={dispatch.status === "ok" ? "dispatch-ok" : "dispatch-failed"}>{dispatch.status === "ok" ? <Check size={16} /> : <TriangleAlert size={16} />}</i><span><strong>{dispatch.channel.toUpperCase()} · {formatNumber(dispatch.delivered)} người nhận</strong><small>{dispatch.detail || dispatch.target}</small></span><time>{dispatch.status === "ok" ? "Đã gửi" : "Cần xử lý"}</time></li>)}</ul> : <p className="panel-empty">Khi một cảnh báo được gửi, nhật ký đa kênh sẽ hiển thị ở đây.</p>}<button type="button" className="panel-link panel-link--button" onClick={retry} disabled={!activeAlert || !token || isBusy}><RefreshCw size={17} /> Xem và gửi lại kênh lỗi <ChevronRight size={17} /></button></section></div>
    <RecipientPanel recipients={snapshot?.recipients ?? []} isBusy={isBusy} onContact={contactRecipient} onRetryAll={retry} /><footer className="dashboard-footer"><UsersRound size={16} /> Quản trị và bản đồ công dân chạy cùng ứng dụng · <Link href="/">mở bản đồ cảnh báo</Link>.</footer>
  </section></main>;
}
